/**/local_planner:
  ros__parameters:
    topics:
      terrain_map: terrain_map                      # Grid map input
      global_plan: global_plan                      # Global RobotPlan input
      local_plan: local_plan                        # Local RobotPlan output
      state:
        ground_truth: state/ground_truth            # Robot state input
      foot_plan_discrete: foot_plan_discrete        # Future foothold output
      foot_plan_continuous: foot_plan_continuous    # Continuous foot trajectory output
      cmd_vel: cmd_vel                              # Twist command input
      control:
        mode: control/mode                          # Control mode input
    map_frame: map                                  # Frame for terrain and plans
