/**/global_body_planner:
  ros__parameters:
    global_body_planner: 
      h_max: 0.76                           # Maximum height of leg base, m
      h_min: 0.35                            # Minimum ground clearance of body corners, m
      h_nom: 0.419                            # Nominal ground clearance of body, m
      v_max: 3.0                              # Maximum robot velocity, m/s
      v_nom: 0.75                             # Nominal velocity, m/s (used during connect function)
      robot_l: 0.85                           # Length of robot body, m
      robot_w: 0.54                           # Width of robot body, m
      robot_h: 0.098                           # Vertical distance between leg base and bottom of robot, m
      mass: 51.0                               # Robot mass, kg
      grf_min: 4.0                            # Minimum GRF in units of body weight (only used for sampling)
      grf_max: 5.0                            # Maximum GRF in units of body weight

/**/local_planner:
  ros__parameters:
    local_planner:
        desired_height: 0.40 # m
        toe_radius: 0.035 # m
    local_footstep_planner:
        hip_clearance: 0.1
        foothold_search_radius: 0.25
        period: 0.36 # s
        ground_clearance: 0.25 # tune
        duty_cycles: [0.5, 0.5, 0.5, 0.5]
        phase_offsets: [0.0, 0.5, 0.5, 0.0] 
    nmpc_controller:
      body:
        x_dim: 12.0
        u_dim: 12.0
        g_dim: 28.0
        x_weights: [5.0, 5.0, 5.0, 0.5, 0.5, 0.5, 0.1, 0.1, 0.2, 0.05, 0.05, 0.01]
        u_weights: [!!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5]
        x_lb: [!!float -2e19, !!float -2e19, 0.0, -3.14159, -3.14159, -3.14159, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19]
        x_ub: [!!float 2e19, !!float 2e19, !!float 2e19, 3.14159, 3.14159, 3.14159, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19]
        x_lb_soft: [!!float -2e19, !!float -2e19, 0.0, -3.14159, -3.14159, -3.14159, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19]
        x_ub_soft: [!!float 2e19, !!float 2e19, !!float 2e19, 3.14159, 3.14159, 3.14159, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19]
        u_lb: [!!float -2e19, !!float -2e19, 10.0, !!float -2e19, !!float -2e19, 10.0, !!float -2e19, !!float -2e19, 10.0, !!float -2e19, !!float -2e19, 10.0]
        u_ub: [!!float 2e19, !!float 2e19, 400.0, !!float 2e19, !!float 2e19, 400.0, !!float 2e19, !!float 2e19, 400.0, !!float 2e19, !!float 2e19, 400.0]
        g_lb: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19]
        g_ub: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      feet:
        x_dim: 24.0
        u_dim: 24.0
        g_dim: 28.0
        x_weights: [7.51, 7.51, 7.51, 7.51, 7.51, 7.51, 7.51, 7.51, 7.51, 7.51, 7.51, 7.51, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111]
        u_weights: [!!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5, !!float 5e-5]
        x_lb: [!!float -2e19, !!float -2e19,  !!float -2e19,  !!float -2e19,  !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19]
        x_ub: [!!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19]
        x_lb_soft: [!!float -2e19, !!float -2e19,  !!float -2e19,  !!float -2e19,  !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19]
        x_ub_soft: [!!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19]
        u_lb: [-99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9, -99.9]
        u_ub: [99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9]
        g_lb: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, !!float -2e19, !!float -2e19,  !!float -2e19,  !!float -2e19]
        g_ub: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19]
      joints:
        x_dim: 24.0
        u_dim: 0.0
        g_dim: 52.0
        x_weights: [0.0]
        u_weights: [0.0]
        x_lb: [-0.707, -1.57, 0.001, -0.707, -1.57, 0.001, -0.707, -1.57, 0.001, -0.707, -1.57, 0.001, -37.71, -37.71, -25.11,-37.71, -37.71, -25.11,-37.71, -37.71, -25.11,-37.71, -37.71, -25.11]
        x_ub: [ 0.707,  3.14,  3.14,  0.707,  3.14,  3.14,  0.707,  3.14,  3.14,  0.707,  3.14,  3.14,  37.71,  37.71,  25.11, 37.71,  37.71,  25.11, 37.71,  37.71,  25.11, 37.71,  37.71,  25.11]
        x_lb_soft: [  -0.5, -1.57,   0.2,   -0.5, -1.57,   0.2,   -0.5, -1.57,   0.2,   -0.5, -1.57,   0.2, -35.0, -35.0, -24.0,-35.0, -35.0, -24.0,-35.0, -35.0, -24.0,-35.0, -35.0, -24.0]
        x_ub_soft: [   0.5,  3.14,   2.8,    0.5,  3.14,   2.8,    0.5,  3.14,   2.8,    0.5,  3.14,   2.8,  35.0,  35.0,  24.0, 35.0,  35.0,  24.0, 35.0,  35.0,  24.0, 35.0,  35.0,  24.0]
        u_lb: [0.0]
        u_ub: [0.0]
        g_lb: [!!float -2e19, !!float -2e19,  !!float -2e19,  !!float -2e19, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, !!float -2e19, !!float -2e19,  !!float -2e19,  !!float -2e19, !!float -2e19, !!float -2e19,  !!float -2e19,  !!float -2e19,  !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19, !!float -2e19]
        g_ub: [!!float 2e19, !!float 2e19,  !!float 2e19,  !!float 2e19, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, !!float 2e19, !!float 2e19,  !!float 2e19,  !!float 2e19, !!float 2e19, !!float 2e19,  !!float 2e19,  !!float 2e19,  !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19, !!float 2e19]
      friction_coefficient: 0.6

/**/robot_driver:
  ros__parameters:
    robot_driver:
      sit_kp: [150.0, 100.0, 100.0]
      sit_kd: [6.0, 6.0, 6.0]
      stand_kp: [120.0, 220.0, 450.0]
      stand_kd: [8.0, 20.0, 35.0]
      stance_kp: [100.0, 180.0, 220.0]
      stance_kd: [10.0, 30.0, 30.0]
      swing_kp: [60.0, 200.0, 200.0]
      swing_kd: [10.0, 30.0, 30.0]
      swing_kp_cart: [0.0, 0.0, 0.0] # N/m
      swing_kd_cart: [0.0, 0.0, 0.0] # N/m
      safety_kp: [0.0, 0.0, 0.0]
      safety_kd: [8.0, 8.0, 8.0]
      stand_joint_angles: [0.0, 1.0, 1.7]
      sit_joint_angles: [0.0, 0.0, 0.0]

/**/controller_manager:
  ros__parameters:
    update_rate: 500
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_controller:
      type: effort_controllers/QuadController

/**/joint_controller:
  ros__parameters:
    topics:
      control:
        joint_command: control/joint_command

/**:
  ros__parameters:
    body:
      frame: "body"
    motor_limits:
      torque: [50000.0, 50000.0, 50000.0]
      speed: [50.0, 50.0, 50.0]
    leg_0:
      joints:
        abad:
          name: "8"
          sign: 1.0
          offset: 0.0
        hip:
          name: "0"
          sign: 1.0
          offset: 0.0
        knee:
          name: "1"
          sign: 1.0
          offset: 0.0
      frames:
        hip: "hip0"
        upper: "upper0"
        lower: "lower0"
        toe: "toe0"
    leg_1: 
      joints:
        abad:
          name: "9"
          sign: 1.0
          offset: 0.0
        hip:
          name: "2"
          sign: 1.0
          offset: 0.0
        knee:
          name: "3"
          sign: 1.0
          offset: 0.0
      frames:
        hip: "hip1"
        upper: "upper1"
        lower: "lower1"
        toe: "toe1"
    leg_2: 
      joints:
        abad:
          name: "10"
          sign: 1.0
          offset: 0.0
        hip:
          name: "4"
          sign: 1.0
          offset: 0.0
        knee:
          name: "5"
          sign: 1.0
          offset: 0.0
      frames:
        hip: "hip2"
        upper: "upper2"
        lower: "lower2"
        toe: "toe2"
    leg_3: 
      joints:
        abad:
          name: "11"
          sign: 1.0
          offset: 0.0
        hip:
          name: "6"
          sign: 1.0
          offset: 0.0
        knee:
          name: "7"
          sign: 1.0
          offset: 0.0
      frames:
        hip: "hip3"
        upper: "upper3"
        lower: "lower3"
        toe: "toe3"
