/* src/Interfaces/config_bonmin.h.  Generated by configure.  */
/* src/Interfaces/config_bonmin.h.in. */

#ifndef __CONFIG_BONMIN_H__
#define __CONFIG_BONMIN_H__

/* Version number of project */
#define BONMIN_VERSION "1.8.9"

/* Major Version number of project */
#define BONMIN_VERSION_MAJOR 1

/* Minor Version number of project */
#define BONMIN_VERSION_MINOR 8

/* Release Version number of project */
#define BONMIN_VERSION_RELEASE 9

#endif
