/**/force_applicator:
  ros__parameters:
    force_applicator:
      fixed:
        force:
          x: 15.0  # Applied force in x direction (N)
          y: 0.0 # Applied force in y direction (N)
          z: 0.0  # Applied force in z direction (N)
        torque:
          x: 0.0 # Applied torque in the x direction (Nm)
          y: 0.0 # Applied torque in the y direction (Nm)
          z: 0.0 # Applied torque in the z direction (Nm)
      duration:
        dt: 0.5 # Duration of Applied Wrench (s)
        update_rate: 100.0
      random:
        force_mag_min: 0.0  #Per Axis Force Manitude
        force_mag_max: 10.0
        torque_mag_min: 0.0 
        torque_mag_max: 0.0 
      periodic:
        period: 2.0
      distance:
        distance_threshold: 1.0

