/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class peak_can_basic_PCANBasic */

#ifndef _Included_peak_can_basic_PCANBasic
#define _Included_peak_can_basic_PCANBasic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    Initialize
 * Signature: (Lpeak/can/basic/TPCANHandle;Lpeak/can/basic/TPCANBaudrate;Lpeak/can/basic/TPCANType;IS)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_Initialize
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jshort);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    InitializeFD
 * Signature: (Lpeak/can/basic/TPCANHandle;Lpeak/can/basic/TPCANBitrateFD;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_InitializeFD
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    Uninitialize
 * Signature: (Lpeak/can/basic/TPCANHandle;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_Uninitialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    Reset
 * Signature: (Lpeak/can/basic/TPCANHandle;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_Reset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    GetStatus
 * Signature: (Lpeak/can/basic/TPCANHandle;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_GetStatus
  (JNIEnv *, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    Read
 * Signature: (Lpeak/can/basic/TPCANHandle;Lpeak/can/basic/TPCANMsg;Lpeak/can/basic/TPCANTimestamp;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_Read
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    ReadFD
 * Signature: (Lpeak/can/basic/TPCANHandle;Lpeak/can/basic/TPCANMsgFD;Lpeak/can/basic/TPCANTimestampFD;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_ReadFD
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    Write
 * Signature: (Lpeak/can/basic/TPCANHandle;Lpeak/can/basic/TPCANMsg;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_Write
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    WriteFD
 * Signature: (Lpeak/can/basic/TPCANHandle;Lpeak/can/basic/TPCANMsgFD;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_WriteFD
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    FilterMessages
 * Signature: (Lpeak/can/basic/TPCANHandle;IILpeak/can/basic/TPCANMode;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_FilterMessages
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    GetValue
 * Signature: (Lpeak/can/basic/TPCANHandle;Lpeak/can/basic/TPCANParameter;Ljava/lang/Object;I)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_GetValue
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    SetValue
 * Signature: (Lpeak/can/basic/TPCANHandle;Lpeak/can/basic/TPCANParameter;Ljava/lang/Object;I)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_SetValue
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    GetErrorText
 * Signature: (Lpeak/can/basic/TPCANStatus;SLjava/lang/StringBuffer;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_GetErrorText
  (JNIEnv *, jobject, jobject, jshort, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    SetRcvEvent
 * Signature: (Lpeak/can/basic/TPCANHandle;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_SetRcvEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    ResetRcvEvent
 * Signature: (Lpeak/can/basic/TPCANHandle;)Lpeak/can/basic/TPCANStatus;
 */
JNIEXPORT jobject JNICALL Java_peak_can_basic_PCANBasic_ResetRcvEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     peak_can_basic_PCANBasic
 * Method:    initializeAPI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_peak_can_basic_PCANBasic_initializeAPI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
