/**/controller_manager:
    ros__parameters:
      update_rate: 500
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      # Position Controllers ---------------------------------
      joint_controller:
        type: effort_controllers/QuadController
        


/**/joint_controller:
  ros__parameters:
      joints:
        - '0'
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
        - '10'
        - '11'
      topics:
        control:
          joint_command: control/joint_command
      limits:
        torque_lims: [21.0, 21.0, 32.0] # For Spirit
        speed_lims: [37.7, 37.7, 25.1] # For Spirit

      
      # Shouldn't be Handled by Controller Manager, moved to ign gazebo sensor modules instead
      # contact_state_publisher:
      #   type: your_contact_plugin/ContactPublisherPlugin  # Placeholder, depends on your actual controller
      #   update_rate: 500 