jobs:
  build-and-test:
    docker:
      - image: osrf/ros:jazzy-desktop-full

    working_directory: /root/ros2_ws/src/quad-sdk

    shell: /bin/bash -eo pipefail

    environment:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - checkout

      - run:
          name: Update packages
          command: |
            apt update

      - run:
          name: Fetch submodules
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive

      - run:
          name: Setup dependencies and build
          command: |
            source /opt/ros/jazzy/setup.bash

            cd /root/ros2_ws/src/quad-sdk
            chmod +x setup.sh
            ./setup.sh

            cd /root/ros2_ws
            colcon build --event-handlers console_direct+ --parallel-workers 1 --executor

      - run:
          name: Run tests
          command: |
            source /opt/ros/jazzy/setup.bash
            source /root/ros2_ws/install/setup.bash

            cd /root/ros2_ws
            colcon test --event-handlers console_direct+ --parallel-workers 1
            colcon test-result --verbose

      - run:
          name: Run soft linting checks
          command: |
            cd /root/ros2_ws/src/quad-sdk
            chmod +x ./scripts/lint_soft.sh
            ./scripts/lint_soft.sh

workflows:
  version: 2
  jazzy-build-and-test:
    jobs:
      - build-and-test