jobs:
  build-and-test:
    working_directory: /ros2_ws/src
    docker:
      - image: osrf/ros:jazzy-desktop-full
    steps:
      - checkout
      - run:
          name: "Update packages"
          command: sudo apt update
      - run:
          name: "Call setup script and build"
          command: |
            source /opt/ros/jazzy/setup.bash
            chmod +x setup.sh
            ./setup.sh
            cd /ros2_ws
            colcon build -j4 -l4
      - run:
          name: "Load ROS params in the background"
          command: |
            source /opt/ros/jazzy/setup.bash
            source /ros2_ws/install/setup.bash
            ros2 launch quad_utils load_global_params.launch load_robot_params:=true
          background: true
      - run:
          name: "Run tests"
          command: |
            cd /ros2_ws
            source /opt/ros/jazzy/setup.bash
            source /ros2_ws/install/setup.bash
            colcon run_tests -j2 -l2 && catkin_test_results
      - run:
          name: "Run soft linting checks"
          command: ./scripts/lint_soft.sh
workflows:
  version: 2
  jazzy-build-and-test:
    jobs:
      - build-and-test
