rviz_interface:
  update_rate: 100
  orientation_subsample: 10
  colors: # Specify as RGB triplets [0,255]
    front_left: [166,25,46]     # Red, a6192e
    back_left: [0,45,114]       # Blue, 002e72
    front_right: [0,132,61]     # Green, 00843d
    back_right: [242,169,0]     # Yellow, f2a900
    net_grf: [55,51,58]         # Black
    individual_grf: [45,31,38]  # Black