/**/cmd_vel_publisher:
  ros__parameters:
    cmd_vel_publisher:
      update_rate: 500.0    # Must Match the Robot Driver
      mode: single          # "single" | "timer" | "off"
      resample_sec: 3.0
      bounds:
        x_min: -1.0
        x_max:  1.0
        y_min: -0.4
        y_max:  0.4
        yaw_min: -1.0
        yaw_max:  1.0
      test_duration: 10.0
      seed: 7
