<package format="2">
  <name>go2w_description</name>
  <version>1.0.0</version>
  <description>
    <p>URDF Description package for go2w_description</p>
    <p>This package contains configuration data, 3D models and launch files for go2w_description robot</p>
  </description>
  <author>David Ologan</author>
  <maintainer email="dologan@andrew.cmu.edu" />
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
