# SPDX-License-Identifier: LGPL-2.1-only
#
# Makefile - Python example Makefile (mainly useful to avoid unknown target
#            errors as well as being able to clean tmp files)
#
# Copyright (C) 2001-2020  PEAK System-Technik GmbH
#
# Contact: <linux@peak-system.com>
# Author:  Stephane Grosjean <s.grosjean@peak-system.com>
#
all:
install:
uninstall:
xeno:
rtai:

clean:
	-rm -f *.pyc
