set(_CATKIN_CURRENT_PACKAGE "tail_controller")
set(tail_controller_VERSION "0.0.0")
set(tail_controller_MAINTAINER "Eleanor Seiler <eseiler@andrew.cmu.edu>")
set(tail_controller_PACKAGE_FORMAT "2")
set(tail_controller_BUILD_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "spirit_msgs" "eigen" "spirit_utils")
set(tail_controller_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "spirit_msgs" "eigen" "spirit_utils")
set(tail_controller_BUILDTOOL_DEPENDS "catkin")
set(tail_controller_BUILDTOOL_EXPORT_DEPENDS )
set(tail_controller_EXEC_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "spirit_msgs" "eigen" "spirit_utils")
set(tail_controller_RUN_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "spirit_msgs" "eigen" "spirit_utils")
set(tail_controller_TEST_DEPENDS )
set(tail_controller_DOC_DEPENDS )
set(tail_controller_URL_WEBSITE "")
set(tail_controller_URL_BUGTRACKER "")
set(tail_controller_URL_REPOSITORY "")
set(tail_controller_DEPRECATED "")