#pragma once

#define ALPAQA_VERSION_MAJOR 1
#define ALPAQA_VERSION_MINOR 0
#define ALPAQA_VERSION_PATCH 0
#define ALPAQA_VERSION_SUFFIX "a8"
#define ALPAQA_VERSION "1.0.0"
#define ALPAQA_VERSION_FULL "1.0.0a8"
