<?xml version="1.0"?>

<!-- file for use with quadruped-sdk ylo2 -->

<robot name="ylo2_description" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find ylo2_description)/xacro/const.xacro"/>
    <xacro:include filename="$(find ylo2_description)/xacro/materials.xacro"/>
    <xacro:include filename="$(find ylo2_description)/xacro/leg.xacro"/>
    <xacro:include filename="$(find ylo2_description)/xacro/gazebo.xacro"/>

    <link name="body">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>

    <joint name="floating_base" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="body"/>
        <child link="trunk"/>
    </joint>

    <link name="trunk">
        <visual name="body_visual">
            <origin rpy="0 0 0" xyz="${body_center_x} ${body_center_y} ${body_center_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_textured_body.dae" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision name="body_collision">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${trunk_length} ${trunk_width} ${trunk_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${trunk_com_x} ${trunk_com_y} ${trunk_com_z}"/>
            <mass value="${trunk_mass}"/>
            <inertia
                ixx="${trunk_ixx}" ixy="${trunk_ixy}" ixz="${trunk_ixz}"
                iyy="${trunk_iyy}" iyz="${trunk_iyz}"
                izz="${trunk_izz}"/>  
        </inertial>
    </link>

    <link name="abad_motors">
        <visual>
            <origin rpy="0 0 0" xyz="${body_center_x} ${body_center_y} ${body_center_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_textured_abad_motors.dae" scale="1 1 1"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <joint name="abad_motors_joint" type="fixed">
        <parent link="trunk"/>
        <child link="abad_motors"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="battery">
        <visual>
            <origin rpy="0 0 0" xyz="${body_center_x} ${body_center_y} ${body_center_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/battery.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="battery_joint" type="fixed">
        <parent link="trunk"/>
        <child link="battery"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="covers">
        <visual>
            <origin rpy="0 0 0" xyz="${body_center_x} ${body_center_y} ${body_center_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_textured_cover.dae" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </visual>
    </link>

    <joint name="covers_joint" type="fixed">
        <parent link="trunk"/>
        <child link="covers"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="accessories">
        <visual>
            <origin rpy="0 0 0" xyz="${body_center_x} ${body_center_y} ${body_center_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/accessories.dae" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="accessories_joint" type="fixed">
        <parent link="trunk"/>
        <child link="accessories"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="d435">
        <visual>
            <origin rpy="0 0 0" xyz="${body_center_x} ${body_center_y} ${body_center_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_d435_textured.dae" scale="1 1 1"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="d435_joint" type="fixed">
        <parent link="trunk"/>
        <child link="d435"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="t265">
        <visual>
            <origin rpy="0 0 0" xyz="${body_center_x} ${body_center_y} ${body_center_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_t265_textured.dae" scale="1 1.06 1.04"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="t265_joint" type="fixed">
        <parent link="trunk"/>
        <child link="t265"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>


    <joint name="imu_joint" type="fixed">
        <parent link="trunk"/>
        <child link="imu_link"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="imu_link">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size=".001 .001 .001"/>
            </geometry>
        </collision>
    </link>

    <!--FL-->
    <xacro:leg suffix="0" mirror="1" mirror_dae="True" front_hind="1" front_hind_dae="True"
               hipJointName="0" kneeJointName="1" abductionJointName="8">
        <origin rpy="0 0 0" xyz="${leg_offset_x+0.0345} ${leg_offset_y+0.006} ${leg_offset_z}"/>
    </xacro:leg>

    <!--RL-->
    <xacro:leg suffix="1" mirror="1" mirror_dae="True" front_hind="-1" front_hind_dae="False"
               hipJointName="2" kneeJointName="3" abductionJointName="9">
        <origin rpy="0 0 0" xyz="${-leg_offset_x-0.0745} ${leg_offset_y+0.006} ${leg_offset_z}"/>
    </xacro:leg>

    <!--FR-->
    <xacro:leg suffix="2" mirror="-1" mirror_dae="False" front_hind="1" front_hind_dae="True"
               hipJointName="4" kneeJointName="5" abductionJointName="10">
        <origin rpy="0 0 0" xyz="${leg_offset_x+0.0345} ${-leg_offset_y+0.005} ${leg_offset_z}"/>
    </xacro:leg>

    <!--RR-->
    <xacro:leg suffix="3" mirror="-1" mirror_dae="False" front_hind="-1" front_hind_dae="False"
               hipJointName="6" kneeJointName="7" abductionJointName="11">
        <origin rpy="0 0 0" xyz="${-leg_offset_x-0.0745} ${-leg_offset_y+0.005} ${leg_offset_z}"/>
    </xacro:leg>

</robot>
