/**/robot_driver:
  ros__parameters:
    topics:
      state:
        imu: state/imu
        joints: state/joints
        ground_truth: state/ground_truth
        estimate: state/estimate
        trajectory: state/trajectory
      local_plan: local_plan
      heartbeat:
        remote: heartbeat/remote
        robot: heartbeat/robot
      body_force:
        joint_torques: body_force/joint_torques
      control:
        grfs: control/grfs
        joint_command: control/joint_command
        mode: control/mode
        single_joint_command: control/single_joint_command
        restart_flag: control/restart_flag
      mocap: /mocap_node/quad/pose
      cmd_vel: cmd_vel
      cmd_vel_stamped: cmd_vel_stamped