function [M,h,J_feet,q_dot] = legDynamics(in1,in2)
%legDynamics
%    [M,H,J_feet,Q_DOT] = legDynamics(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    26-Jun-2025 01:52:01

feet_location1 = in2(1,:);
feet_location2 = in2(2,:);
feet_location3 = in2(3,:);
feet_location4 = in2(4,:);
feet_location5 = in2(5,:);
feet_location6 = in2(6,:);
feet_location7 = in2(7,:);
feet_location8 = in2(8,:);
feet_location9 = in2(9,:);
feet_location10 = in2(10,:);
feet_location11 = in2(11,:);
feet_location12 = in2(12,:);
omega1 = in1(10,:);
omega2 = in1(11,:);
omega3 = in1(12,:);
p_dot1 = in1(7,:);
p_dot2 = in1(8,:);
p_dot3 = in1(9,:);
theta1 = in1(4,:);
theta2 = in1(5,:);
theta3 = in1(6,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
mt1 = [1.6247e+1,0.0,0.0,0.0,0.0,0.0,0.0,1.6247e+1,0.0,0.0,0.0,0.0,0.0,0.0,1.6247e+1,0.0,0.0,0.0,0.0,0.0,0.0,6.96808189485125e-2,t2.*1.2166e-4-t5.*1.534235398809762e-3];
mt2 = [t6.*(-6.96808189485125e-2)+t2.*t3.*1.534235398809762e-3+t3.*t5.*1.2166e-4,0.0,0.0,0.0,1.2166e-4];
mt3 = [t2.*5.623873898131058e-1+t5.*3.12e-5,t6.*(-1.2166e-4)-t2.*t3.*3.12e-5+t3.*t5.*5.623873898131058e-1,0.0,0.0,0.0];
mt4 = [1.534235398809762e-3,t2.*(-3.12e-5)-t5.*6.160186593645933e-1];
mt5 = [t6.*(-1.534235398809762e-3)+t2.*t3.*6.160186593645933e-1-t3.*t5.*3.12e-5];
M = reshape([mt1,mt2,mt3,mt4,mt5],6,6);
if nargout > 1
    t7 = sin(theta3);
    t8 = omega1.^2;
    t9 = omega2.^2;
    t10 = omega3.^2;
    et1 = omega2.*(omega1.*1.534235398809762e-3-omega2.*3.12e-5+omega3.*6.160186593645933e-1);
    et2 = -omega3.*(omega1.*1.2166e-4+omega2.*5.623873898131058e-1-omega3.*3.12e-5);
    et3 = t2.*t8.*(-1.534235398809762e-3)+t2.*t10.*1.534235398809762e-3-t5.*t8.*1.2166e-4+t5.*t9.*1.2166e-4+omega1.*omega2.*t2.*3.12e-5;
    et4 = omega1.*omega3.*t2.*(-5.463378404160808e-1)+omega2.*omega3.*t2.*1.2166e-4-omega1.*omega2.*t5.*4.927065708645933e-1+omega1.*omega3.*t5.*3.12e-5+omega2.*omega3.*t5.*1.534235398809762e-3;
    et5 = t6.*t9.*3.12e-5-t6.*t10.*3.12e-5-omega1.*omega2.*t6.*1.534235398809762e-3+omega1.*omega3.*t6.*1.2166e-4-omega2.*omega3.*t6.*5.363126955148756e-2;
    et6 = t2.*t3.*t8.*1.2166e-4-t2.*t3.*t9.*1.2166e-4-t3.*t5.*t8.*1.534235398809762e-3+t3.*t5.*t10.*1.534235398809762e-3+omega1.*omega2.*t2.*t3.*4.927065708645933e-1;
    et7 = omega1.*omega3.*t2.*t3.*(-3.12e-5)-omega2.*omega3.*t2.*t3.*1.534235398809762e-3+omega1.*omega2.*t3.*t5.*3.12e-5-omega1.*omega3.*t3.*t5.*5.463378404160808e-1;
    et8 = omega2.*omega3.*t3.*t5.*1.2166e-4;
    h = [0.0;0.0;1.5938307e+2;et1+et2;et3+et4;et5+et6+et7+et8];
end
if nargout > 2
    mt6 = [1.0,0.0,0.0,-feet_location2.*t6-feet_location3.*t3.*t7,-feet_location3.*t4,feet_location2,0.0,1.0,0.0,feet_location1.*t6+feet_location3.*t3.*t4,-feet_location3.*t7,-feet_location1,0.0,0.0,1.0,-t3.*(feet_location2.*t4-feet_location1.*t7),feet_location1.*t4+feet_location2.*t7,0.0,1.0,0.0,0.0,-feet_location5.*t6-feet_location6.*t3.*t7,-feet_location6.*t4,feet_location5,0.0,1.0,0.0,feet_location4.*t6+feet_location6.*t3.*t4,-feet_location6.*t7,-feet_location4,0.0,0.0,1.0,-t3.*(feet_location5.*t4-feet_location4.*t7),feet_location4.*t4+feet_location5.*t7,0.0,1.0,0.0,0.0,-feet_location8.*t6-feet_location9.*t3.*t7,-feet_location9.*t4,feet_location8,0.0,1.0,0.0,feet_location7.*t6+feet_location9.*t3.*t4,-feet_location9.*t7,-feet_location7,0.0,0.0,1.0,-t3.*(feet_location8.*t4-feet_location7.*t7),feet_location7.*t4+feet_location8.*t7,0.0,1.0,0.0,0.0];
    mt7 = [-feet_location11.*t6-feet_location12.*t3.*t7,-feet_location12.*t4,feet_location11,0.0,1.0,0.0,feet_location10.*t6+feet_location12.*t3.*t4,-feet_location12.*t7,-feet_location10,0.0,0.0,1.0,-t3.*(feet_location11.*t4-feet_location10.*t7),feet_location10.*t4+feet_location11.*t7,0.0];
    J_feet = reshape([mt6,mt7],6,12);
end
if nargout > 3
    t11 = 1.0./t3;
    q_dot = [p_dot1;p_dot2;p_dot3;t11.*(omega1.*t3+omega3.*t2.*t6+omega2.*t5.*t6);omega2.*t2-omega3.*t5;t11.*(omega3.*t2+omega2.*t5)];
end
end
