function [M,h,J_feet,q_dot] = legDynamics(in1,in2)
%legDynamics
%    [M,H,J_feet,Q_DOT] = legDynamics(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    20-Feb-2024 15:52:38

feet_location1 = in2(1,:);
feet_location2 = in2(2,:);
feet_location3 = in2(3,:);
feet_location4 = in2(4,:);
feet_location5 = in2(5,:);
feet_location6 = in2(6,:);
feet_location7 = in2(7,:);
feet_location8 = in2(8,:);
feet_location9 = in2(9,:);
feet_location10 = in2(10,:);
feet_location11 = in2(11,:);
feet_location12 = in2(12,:);
omega1 = in1(10,:);
omega2 = in1(11,:);
omega3 = in1(12,:);
p_dot1 = in1(7,:);
p_dot2 = in1(8,:);
p_dot3 = in1(9,:);
theta1 = in1(4,:);
theta2 = in1(5,:);
theta3 = in1(6,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
mt1 = [1.33e+2./1.0e+1,0.0,0.0,0.0,0.0,0.0,0.0,1.33e+2./1.0e+1,0.0,0.0,0.0,0.0,0.0,0.0,1.33e+2./1.0e+1,0.0,0.0,0.0,0.0,0.0,0.0,1.210223262608696e-1,0.0,t6.*(-1.210223262608696e-1),0.0,0.0,0.0,0.0,t2.*4.312504678017391e-1,t3.*t5.*4.312504678017391e-1,0.0,0.0,0.0,0.0];
mt2 = [t5.*(-4.880293158017391e-1),t2.*t3.*4.880293158017391e-1];
M = reshape([mt1,mt2],6,6);
if nargout > 1
    mt3 = [0.0;0.0;1.30473e+2;omega2.*omega3.*5.677884800000005e-2;omega1.*(omega3.*t2.*2.644564066141804e+16+omega2.*t5.*2.235429348229282e+16).*(-1.387778780781446e-17)];
    mt4 = [omega2.*omega3.*t6.*(-5.677884800000005e-2)+omega1.*omega2.*t2.*t3.*3.102281415408695e-1-omega1.*omega3.*t3.*t5.*3.670069895408696e-1];
    h = [mt3;mt4];
end
if nargout > 2
    t7 = sin(theta3);
    mt5 = [1.0,0.0,0.0,-feet_location2.*t6-feet_location3.*t3.*t7,-feet_location3.*t4,feet_location2,0.0,1.0,0.0,feet_location1.*t6+feet_location3.*t3.*t4,-feet_location3.*t7,-feet_location1,0.0,0.0,1.0,-t3.*(feet_location2.*t4-feet_location1.*t7),feet_location1.*t4+feet_location2.*t7,0.0,1.0,0.0,0.0,-feet_location5.*t6-feet_location6.*t3.*t7,-feet_location6.*t4,feet_location5,0.0,1.0,0.0,feet_location4.*t6+feet_location6.*t3.*t4,-feet_location6.*t7,-feet_location4,0.0,0.0,1.0,-t3.*(feet_location5.*t4-feet_location4.*t7),feet_location4.*t4+feet_location5.*t7,0.0,1.0,0.0,0.0,-feet_location8.*t6-feet_location9.*t3.*t7,-feet_location9.*t4,feet_location8,0.0,1.0,0.0,feet_location7.*t6+feet_location9.*t3.*t4,-feet_location9.*t7,-feet_location7,0.0,0.0,1.0,-t3.*(feet_location8.*t4-feet_location7.*t7),feet_location7.*t4+feet_location8.*t7,0.0,1.0,0.0,0.0];
    mt6 = [-feet_location11.*t6-feet_location12.*t3.*t7,-feet_location12.*t4,feet_location11,0.0,1.0,0.0,feet_location10.*t6+feet_location12.*t3.*t4,-feet_location12.*t7,-feet_location10,0.0,0.0,1.0,-t3.*(feet_location11.*t4-feet_location10.*t7),feet_location10.*t4+feet_location11.*t7,0.0];
    J_feet = reshape([mt5,mt6],6,12);
end
if nargout > 3
    t8 = 1.0./t3;
    q_dot = [p_dot1;p_dot2;p_dot3;t8.*(omega1.*t3+omega3.*t2.*t6+omega2.*t5.*t6);omega2.*t2-omega3.*t5;t8.*(omega3.*t2+omega2.*t5)];
end
end
