/**/body_force_estimator:
  ros__parameters:
    body_force_estimator:
      update_rate: 250.0                     # Observer loop rate, Hz
      K_O: 25.0                              # Momentum observer gain
      cancel_friction: 1                     # Subtract joint friction model from estimate
