/**/body_force_estimator:
  ros__parameters:
    topics:
      state:
        ground_truth: state/ground_truth
      local_plan: local_plan
      body_force:
        joint_torques: body_force/joint_torques
        toe_forces: body_force/toe_forces

